import "./globals.css";
import { Providers } from "@/components/pages/sign/provider";

export const metadata = {
  title: "Chatting Extension App",
  description: "Generated by Ramir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
