import "./globals.css";
import { Providers } from "@/components/pages/sign/provider";
import store from "@/redux/store";
import { Provider } from "react-redux";

export const metadata = {
  title: "Chatting Extension App",
  description: "Generated by Ramir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Provider store={store}>
          <Providers>{children}</Providers>
        </Provider>
      </body>
    </html>
  );
}
